/**
 * Auto-generated by: yarn db:types
 * DO NOT EDIT — run `yarn db:types` after any migration to regenerate.
 */
export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export type Database = {
  public: {
    Tables: {
      // ── microCMS ──────────────────────────────────────────────────────────
      cms_pages: {
        Row: {
          id: string; slug: string; locale: string; title: string | null
          published: boolean; meta_title: string | null; meta_desc: string | null
          created_at: string; updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['cms_pages']['Row'], 'id' | 'created_at' | 'updated_at'>
        Update: Partial<Database['public']['Tables']['cms_pages']['Insert']>
      }
      cms_content_blocks: {
        Row: {
          id: string; page_slug: string; key: string; locale: string
          value: string | null; type: string; updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['cms_content_blocks']['Row'], 'id' | 'updated_at'>
        Update: Partial<Database['public']['Tables']['cms_content_blocks']['Insert']>
      }
      cms_feature_flags: {
        Row: { id: string; key: string; enabled: boolean; description: string | null; updated_at: string }
        Insert: Omit<Database['public']['Tables']['cms_feature_flags']['Row'], 'id' | 'updated_at'>
        Update: Partial<Database['public']['Tables']['cms_feature_flags']['Insert']>
      }
      cms_navigation: {
        Row: {
          id: string; location: string; label: string; href: string
          locale: string; order: number; visible: boolean
        }
        Insert: Omit<Database['public']['Tables']['cms_navigation']['Row'], 'id'>
        Update: Partial<Database['public']['Tables']['cms_navigation']['Insert']>
      }
      cms_media: {
        Row: { id: string; key: string; storage_path: string; alt_text: string | null; uploaded_at: string }
        Insert: Omit<Database['public']['Tables']['cms_media']['Row'], 'id' | 'uploaded_at'>
        Update: Partial<Database['public']['Tables']['cms_media']['Insert']>
      }
      // ── microCRM ──────────────────────────────────────────────────────────
      crm_contacts: {
        Row: {
          id: string; email: string; first_name: string | null; last_name: string | null
          company: string | null; role: string | null; phone: string | null
          source: string | null; tags: string[]; notes: string | null
          created_at: string; updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['crm_contacts']['Row'], 'id' | 'created_at' | 'updated_at'>
        Update: Partial<Database['public']['Tables']['crm_contacts']['Insert']>
      }
      crm_leads: {
        Row: {
          id: string; contact_id: string; status: Database['public']['Enums']['lead_status']
          priority: string | null; project_type: Database['public']['Enums']['project_type'] | null
          engagement_model: Database['public']['Enums']['engagement_model'] | null
          timeline: Database['public']['Enums']['timeline_option'] | null
          estimated_value: number | null; currency: string
          assigned_to: string | null; closed_at: string | null
          created_at: string; updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['crm_leads']['Row'], 'id' | 'created_at' | 'updated_at'>
        Update: Partial<Database['public']['Tables']['crm_leads']['Insert']>
      }
      crm_project_requests: {
        Row: {
          id: string; contact_id: string | null; lead_id: string | null
          first_name: string; last_name: string; email: string; company: string | null
          project_type: Database['public']['Enums']['project_type'] | null
          engagement_model: Database['public']['Enums']['engagement_model'] | null
          timeline: Database['public']['Enums']['timeline_option'] | null
          message: string | null; locale: string; ip_address: string | null
          read: boolean; created_at: string
        }
        Insert: Omit<Database['public']['Tables']['crm_project_requests']['Row'], 'id' | 'created_at'>
        Update: Partial<Database['public']['Tables']['crm_project_requests']['Insert']>
      }
      crm_interactions: {
        Row: {
          id: string; contact_id: string | null; lead_id: string | null
          type: Database['public']['Enums']['interaction_type']
          title: string; body: string | null; metadata: Json
          created_by: string | null; created_at: string
        }
        Insert: Omit<Database['public']['Tables']['crm_interactions']['Row'], 'id' | 'created_at'>
        Update: Partial<Database['public']['Tables']['crm_interactions']['Insert']>
      }
      crm_newsletter_subscribers: {
        Row: {
          id: string; email: string; first_name: string | null; locale: string
          status: string; consent_given_at: string | null; unsubscribed_at: string | null
          source: string | null; tags: string[]; created_at: string
        }
        Insert: Omit<Database['public']['Tables']['crm_newsletter_subscribers']['Row'], 'id' | 'created_at'>
        Update: Partial<Database['public']['Tables']['crm_newsletter_subscribers']['Insert']>
      }
      crm_newsletter_campaigns: {
        Row: {
          id: string; title: string; subject: string | null; status: string; segment: string
          sent_count: number; open_count: number; click_count: number; unsub_count: number
          scheduled_at: string | null; sent_at: string | null; created_at: string
        }
        Insert: Omit<Database['public']['Tables']['crm_newsletter_campaigns']['Row'], 'id' | 'created_at'>
        Update: Partial<Database['public']['Tables']['crm_newsletter_campaigns']['Insert']>
      }
      profiles: {
        Row: { id: string; email: string; full_name: string | null; role: string; created_at: string }
        Insert: Omit<Database['public']['Tables']['profiles']['Row'], 'created_at'>
        Update: Partial<Database['public']['Tables']['profiles']['Insert']>
      }
    }
    Views: { [_ in never]: never }
    Functions: { [_ in never]: never }
    Enums: {
      lead_status: 'new' | 'qualified' | 'proposal' | 'negotiation' | 'won' | 'lost'
      project_type: 'new_application' | 'integration' | 'support_evolution' | 'not_sure'
      engagement_model: 'fixed_scope' | 'time_based' | 'not_sure'
      timeline_option: 'ready_now' | '1_3_months' | '3_6_months' | 'exploring'
      interaction_type:
        | 'form_submission' | 'email_sent' | 'email_received'
        | 'call' | 'meeting' | 'note' | 'status_change'
        | 'proposal_sent' | 'contract_signed'
    }
  }
}
